<?php

namespace App\Repositories;

use App\Models\Job_status;
use App\Repositories\BaseRepository;

/**
 * Class Job_statusRepository
 * @package App\Repositories
 * @version January 20, 2021, 2:18 am UTC
*/

class Job_statusRepository extends BaseRepository
{
    /**
     * @var array
     */
    protected $fieldSearchable = [
        'name',
        'code',
        'description',
        'created_by',
        'modified_by'
    ];

    /**
     * Return searchable fields
     *
     * @return array
     */
    public function getFieldsSearchable()
    {
        return $this->fieldSearchable;
    }

    /**
     * Configure the Model
     **/
    public function model()
    {
        return Job_status::class;
    }
    public function create($input)
    {
        return parent::create($input); // TODO: Change the autogenerated stub
    }
    public function update($input, $id)
    {
        return parent::update($input, $id); // TODO: Change the autogenerated stub
    }
    public function delete($id)
    {
        return parent::delete($id); // TODO: Change the autogenerated stub
    }
    public function paginate($search = [], $perPage = null, $columns = null, $orders = [])
    {
        return parent::paginate($search, $perPage, $columns, $orders); // TODO: Change the autogenerated stub
    }
}
