<?php

namespace App\Repositories;

use App\Models\Positions;
use App\Repositories\BaseRepository;

/**
 * Class PositionsRepository
 * @package App\Repositories
 * @version January 18, 2021, 10:02 am UTC
 */
class PositionsRepository extends BaseRepository
{
    /**
     * @var array
     */
    protected $fieldSearchable = [
        'name',
        'code',
        'description'
    ];
    protected $fieldInList = [
        'id',
        'name',
        'code',
        'description',
        'created_by',
        'modified_by'
    ];

    protected $fieldFilter = [
        'name',
        'code'

    ];

    public $fieldOrder = [
        'id'
    ];

    /**
     * Return searchable fields
     *
     * @return array
     */
    public function getFieldsSearchable()
    {
        return $this->fieldSearchable;
    }

    /**
     * Configure the Model
     **/
    public function model()
    {
        return Positions::class;
    }

    public function create($input)
    {
        return parent::create($input);
    }

    public function update($input, $id)
    {
        return parent::update($input, $id);
    }

    public function paginate($search = [], $perPage = null, $columns = null, $orders = [])
    {
        return parent::paginate($search, $perPage, $columns, $orders);
    }
//    public function delete($id)
//    {
//        return parent::delete($id); // TODO: Change the autogenerated stub
//    }
}
